
return {
  { internalName = "IC2:itemCofeeBeans", displayName = "Кофейные зёрна", price_coin = 0.00, price_ema = 1.00 },
  { internalName = "metadrive:block_reactor_coolant_injector", displayName = "Впрыскиватель хладагента", price_coin = 480.00, price_ema = 0.00 },
  { internalName = "minecraft:dye", displayName = "Чернильный мешок", price_coin = 1.10, price_ema = 0.00 },
  { internalName = "BuildCraft|Silicon:laserTableBlock", displayName = "Сборочный стол", price_coin = 0.00, price_ema = 2.81 },
  { internalName = "minecraft:apple", displayName = "Яблоко", price_coin = 0.00, price_ema = 0.02 },
  { internalName = "EnderIO:itemAlloy", displayName = "Призрачный сплав", price_coin = 1.00, price_ema = 0.00, damage = 7 },
  { internalName = "EnderIO:blockSagMill", displayName = "Дробитель (Ender IO)", price_coin = 13.00, price_ema = 0.00 },
  { internalName = "EnderIO:blockAlloySmelter", displayName = "Завод сплавов", price_coin = 19.00, price_ema = 0.00, damage = 4 },
  { internalName = "EnderIO:itemBasicCapacitor", displayName = "Мелодичный конденсатор", price_coin = 0.00, price_ema = 310.58, damage = 4 },
  { internalName = "EnderIO:itemBasicCapacitor", displayName = "Кристаллический конденсатор", price_coin = 340.00, price_ema = 0.00,  damage = 3 },
  { internalName = "minecraft:potion", displayName = "Лечебное зелье", price_coin = 0.00, price_ema = 0.3, damage = 8197 },
  { internalName = "minecraft:potion", displayName = "Зелье невидимости (3:00)", price_coin = 0.00, price_ema = 0.3, damage = 8206 },
  { internalName = "minecraft:potion", displayName = "Зелье замедления (4:00)", price_coin = 0.00, price_ema = 0.3, damage = 8266 },
  { internalName = "minecraft:potion", displayName = "Зелье замедления (1:30)", price_coin = 0.00, price_ema = 0.3, damage = 8202 },
  { internalName = "minecraft:potion", displayName = "Зелье слабости (4:00)", price_coin = 0.00, price_ema = 0.3, damage = 8264 },
  { internalName = "minecraft:potion", displayName = "Зелье слабости (1:30)", price_coin = 0.00, price_ema = 0.3, damage = 8200 },
  { internalName = "minecraft:potion", displayName = "Зелье регенерации (2:00)", price_coin = 0.00, price_ema = 0.2, damage = 8257 },
  { internalName = "minecraft:potion", displayName = "Зелье регенерации (0:45)", price_coin = 0.00, price_ema = 0.2, damage = 8193 },
  { internalName = "minecraft:potion", displayName = "Зелье вреда", price_coin = 0.00, price_ema = 0.2,  damage = 8204 },
  { internalName = "minecraft:potion", displayName = "Зелье подводного дыхания (3:00)", price_coin = 0.00, price_ema = 0.2, damage = 8205 },
  { internalName = "minecraft:potion", displayName = "Зелье огнестойкости (3:00)", price_coin = 0.00, price_ema = 0.2, damage = 8195 },
  { internalName = "minecraft:potion", displayName = "Зелье ночного зрения (3:00)", price_coin = 0.00, price_ema = 0.1, damage = 8198 },
  { internalName = "minecraft:potion", displayName = "Зелье стремительности (8:00)", price_coin = 0.00, price_ema = 0.2, damage = 8258 },
  { internalName = "minecraft:potion", displayName = "Зелье стремительности (3:00)", price_coin = 0.00, price_ema = 0.2, damage = 8194 },
  { internalName = "minecraft:potion", displayName = "Зелье силы (8:00)", price_coin = 0.00, price_ema = 0.2, damage = 8265 },
  { internalName = "minecraft:potion", displayName = "Зелье силы (3:00)", price_coin = 0.00, price_ema = 0.2, damage = 8201 },
  { internalName = "minecraft:potion", displayName = "Зелье отравления II", price_coin = 0.00, price_ema = 0.1, damage = 8228 },
  { internalName = "minecraft:potion", displayName = "Зелье отравления (2:00)", price_coin = 0.00, price_ema = 0.1, damage = 8260 },
  { internalName = "minecraft:potion", displayName = "Зелье отравления (0:45)", price_coin = 0.00, price_ema = 0.1, damage = 8196 },
  { internalName = "minecraft:potion", displayName = "Зелье ночного зрения (8:00)", price_coin = 0.00, price_ema = 0.1, damage = 8262 },
  { internalName = "minecraft:potion", displayName = "Зелье подводного дыхания (8:00)", price_coin = 0.00, price_ema = 0.2, damage = 8269 },
  { internalName = "minecraft:potion", displayName = "Зелье регенерации II", price_coin = 0.00, price_ema = 0.2, damage = 8225 },
  { internalName = "minecraft:potion", displayName = "Зелье вреда II", price_coin = 0.00, price_ema = 0.2, damage = 8236 },
  { internalName = "minecraft:potion", displayName = "Лечебное зелье II", price_coin = 0.00, price_ema = 0.2, damage = 8229 },
  { internalName = "minecraft:potion", displayName = "Зелье огнестойкости (8:00)", price_coin = 0.00, price_ema = 0.2, damage = 8259 },
  { internalName = "minecraft:potion", displayName = "Зелье стремительности II", price_coin = 0.00, price_ema = 0.2, damage = 8226 },
  { internalName = "minecraft:potion", displayName = "Зелье невидимости (8:00)", price_coin = 0.00, price_ema = 0.2, damage = 8270 },
  { internalName = "minecraft:potion", displayName = "Зелье силы II", price_coin = 0.00, price_ema = 0.2, damage = 8233 },
  { internalName = "minecraft:melon", displayName = "Ломтик арбуза", price_coin = 1.00, price_ema = 0.00 },
  { internalName = "EnderIO:itemBasicCapacitor", displayName = "Восьмислойный конденсатор", price_coin = 40.00, price_ema = 0.00, damage = 2 },
  { internalName = "minecraft:fish", displayName = "Рыба фугу", price_coin = 0.00, price_ema = 0.5, damage = 3 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Заряженный кристалл истинного кварца", price_coin = 0.00, price_ema = 0.2, damage = 7 },
  { internalName = "OpenComputers:cable", displayName = "Кабель", price_coin = 0.00, price_ema = 0.03 },
  { internalName = "OpenComputers:item", displayName = "Жёсткий диск (3-ий уровень)", price_coin = 0.00, price_ema = 5.50, damage = 7 },
  { internalName = "OpenComputers:eeprom", displayName = "EEPROM (Lua Bios)", price_coin = 0.00, price_ema = 0.50 },
  { internalName = "OpenComputers:keyboard", displayName = "Клавиатура", price_coin = 0.00, price_ema = 0.10 },
  { internalName = "IC2:itemOreIridium", displayName = "Иридиевая руда", price_coin = 0.00, price_ema = 10.00 },
  { internalName = "dwcity:Amber", displayName = "Янтарь", price_coin = 0.00, price_ema = 20.00 },
  { internalName = "dwcity:Amethyst", displayName = "Аметист", price_coin = 0.00, price_ema = 53.62 },
  { internalName = "IC2:itemUran235small", displayName = "Кусочек урана-235", price_coin = 0.00, price_ema = 0.03 },
  { internalName = "Forestry:honeydew", displayName = "Медвяная роса", price_coin = 0.00, price_ema = 0.01 },
  { internalName = "Forestry:fruits", displayName = "Каштан", price_coin = 0.00, price_ema = 0.02, damage = 3 },
  { internalName = "Forestry:pollen", displayName = "Скопление пыльцы", price_coin = 0.00, price_ema = 0.05 },
  { internalName = "Forestry:craftingMaterial", displayName = "Тканый шёлк", price_coin = 0.00, price_ema = 14.40, damage = 3 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ монитор хранения", price_coin = 8.50, price_ema = 0.00, damage = 400 },
  { internalName = "IC2:itemScrap", displayName = "Утильсырьё", price_coin = 0.11, price_ema = 0.00 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Кремниевый пресс для высекателя", price_coin = 0.00, price_ema = 8.00, damage = 19 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Логический пресс для высекателя", price_coin = 0.00, price_ema = 8.00, damage = 15 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Вычислительный пресс для высекателя", price_coin = 0.00, price_ema = 8.00, damage = 13 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Инженерный пресс для высекателя", price_coin = 0.00, price_ema = 8.00, damage = 14 },
  { internalName = "ThermalDynamics:ThermalDynamics_0", displayName = "Криостабилизированная флаксовая труба", price_coin = 14.00, price_ema = 0.00, damage = 6 },
  { internalName = "ThermalExpansion:Machine", displayName = "Резонирующая красаня печ", price_coin = 81.00, price_ema = 0.00 },
  { internalName = "ThermalDynamics:retriever", displayName = "Резонирующий поисковик", price_coin = 20.00, price_ema = 0.00, damage = 4 },
  { internalName = "ThermalDynamics:servo", displayName = "Резонирующий сервомеханизм", price_coin = 19.50, price_ema = 0.00, damage = 4 },
  { internalName = "appliedenergistics2:tile.BlockQuartzGlass", displayName = "Кварцевое стекло", price_coin = 0.00, price_ema = 0.01 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Карта ёмкости", price_coin = 5.50, price_ema = 0.00, damage = 27 },
  { internalName = "IC2:itemCellEmpty", displayName = "Капсула хладогента", price_coin = 5.00, price_ema = 0.00, damage = 9 },
  { internalName = "appliedenergistics2:tile.BlockIOPort", displayName = "МЭ порт ввода вывода", price_coin = 36.00, price_ema = 0.05 },
  { internalName = "ThermalExpansion:Glass", displayName = "Закалённое стекло", price_coin = 0.00, price_ema = 0.05 },
  { internalName = "IC2:reactorPlatingHeat", displayName = "Теплоёмкая реакторная пластина", price_coin = 10.00, price_ema = 0.00 },
  { internalName = "IC2:reactorCoolantSix", displayName = "Охлаждающий стержень 60к", price_coin = 73.00, price_ema = 0.00 },
  { internalName = "IC2:reactorCoolantTriple", displayName = "Охлаждающий стержень 30к", price_coin = 33.00, price_ema = 0.00 },
  { internalName = "IC2:reactorCoolantSimple", displayName = "Охлаждающий стержень 10к", price_coin = 9.00, price_ema = 0.00 },
  { internalName = "IC2:itemBatLamaCrystal", displayName = "Лазуротроновый кристалл", price_coin = 39.50, price_ema = 0.00 },
  { internalName = "appliedenergistics2:tile.BlockInterface", displayName = "МЭ интерфейс", price_coin = 9.80, price_ema = 0.00 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ стеклянный кабель - Изменчивый", price_coin = 1.20, price_ema = 0.00, damage = 16 },
  { internalName = "IC2:blockMachine", displayName = "Дробитель", price_coin = 11.80, price_ema = 0.00, damage = 3 },
  { internalName = "IC2:blockMachine", displayName = "Компрессор", price_coin = 11.80, price_ema = 0.00, damage = 5 },
  { internalName = "IC2:reactorHeatSwitchSpread", displayName = "Компонентный теплообменик", price_coin = 15.80, price_ema = 0.00 },
  { internalName = "IC2:reactorVentGold", displayName = "Разогнанный теплоотвод", price_coin = 25.00, price_ema = 0.00 },
  { internalName = "IC2:reactorVentSpread", displayName = "Компонентный теплоотвод", price_coin = 16.80, price_ema = 0.00 },
  { internalName = "appliedenergistics2:tile.ItemBlockMaterial", displayName = "Отпечатанный кремний", price_coin = 1.00, price_ema = 0.00 },
  { internalName = "appliedenergistics2:tile.BlockInscriber", displayName = "Высекатель", price_coin = 10.00, price_ema = 0.00 },
  { internalName = "appliedenergistics2:tile.BlockCharger", displayName = "Зарядник", price_coin = 8.60, price_ema = 0.00 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Карта ускорения", price_coin = 8.30, price_ema = 0.00, damage = 30 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Карта создания", price_coin = 3.50, price_ema = 0.00, damage = 53 },
  { internalName = "dwcity:Fire_materia", displayName = "Солнечная Материя", price_coin = 18.66, price_ema = 1.24 },
  { internalName = "dwcity:Vis_materia", displayName = "Вис Материя", price_coin = 23.1, price_ema = 1.54 },
  { internalName = "dwcity:Live_materia", displayName = "Живая Материя", price_coin = 15.6, price_ema = 1.04 },
  { internalName = "dwcity:Dark_materia", displayName = "Тёмная Материя", price_coin = 16.2, price_ema = 1.08 },
  { internalName = "dwcity:Sky_materia", displayName = "Ледяная Материя", price_coin = 15.6, price_ema = 1.04 },
  { internalName = "ExtraTrees:food", displayName = "Кокос", price_coin = 1.00, price_ema = 0.01, damage = 50 },
  { internalName = "GraviSuite:vajra", displayName = "Ваджра", price_coin = 1000.50, price_ema = 200.00 },
  { internalName = "dwcity:Powder11", displayName = "Трижды сжатый камень", price_coin = 180.00, price_ema = 0.00 },
  { internalName = "dwcity:Powder7", displayName = "Дважды сжатый адский кирпич", price = 555.55, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ плотный кабель - Изменчивый", price = 7.50, currency = "res", damage = 76 },
  { internalName = "ae2stuff:Cable", displayName = "МЭ улучшенный кабель - Изменчивый", price = 2.82, currency = "res", damage = 16 },
  { internalName = "Forestry:craftingMaterial", displayName = "Пропитанная обшивка", price = 2.50, currency = "res", damage = 6 },
  { internalName = "Forestry:oakStick", displayName = "Полированная палка", price = 1.50, currency = "res" },
  { internalName = "metadrive:block_compressor", displayName = "Квантовый компрессор", price_coin = 784.61, price_ema = 18.25 },
  { internalName = "metadrive:block_thermal_smelter", displayName = "Квантовая индукционная плавильня", price = 770.00, currency = "res" },
  { internalName = "metadrive:block_advanced_squeezer", displayName = "Квантовая соковыжималка", price_coin = 641.90, price_ema = 16.29 },
  { internalName = "metadrive:block_ic2_centrifuge", displayName = "Квантовая термальная центрифуга", price_coin = 750.70, price_ema = 16.30 },
  { internalName = "metadrive:block_advanced_carpenter", displayName = "Квантовый плотник", price_coin = 732.64, price_ema = 18.32 },
  { internalName = "metadrive:block_extractor", displayName = "Квантовый экстрактор", price_coin = 650.88, price_ema = 16.27 },
  { internalName = "metadrive:block_ore_washing", displayName = "Квантовый рудопромывочный механизм", price_coin = 672.16, price_ema = 16.80 },
  { internalName = "metadrive:block_lava_generator", displayName = "Квантовый производитель лавы", price_coin = 747.40, price_ema = 19.00 },
  { internalName = "metadrive:block_macverator", displayName = "Квантовый дробитель", price_coin = 732.24, price_ema = 8.14 },
  { internalName = "metadrive:block_furnace", displayName = "Квантовая печь", price_coin = 730.44, price_ema = 8.12 },
  { internalName = "metadrive:block_metal_former", displayName = "Квантовый металлоформовочный механизм", price_coin = 663.40, price_ema = 16.58 },
  { internalName = "Forestry:propolis", displayName = "Прополис", price = 0.30, currency = "res" },
  { internalName = "minecraft:leather", displayName = "Кожа", price = 0.30, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockController", displayName = "МЭ контроллер", price = 22.5, currency = "res" },
  { internalName = "luxinfineitems:CompressedCPU", displayName = "Контроллер автокрафта", price = 375.21, currency = "res" },
  { internalName = "EnderIO:itemPowerConduit", displayName = "Энергопровод из вибрирующего сплава ", price = 5.00, currency = "res", damage = 2 },
  { internalName = "EnderIO:itemLiquidConduit", displayName = "Жидкостная труба из мелодичного сплава", price = 5.00, currency = "res", damage = 5 },
  { internalName = "dwcity:Radio_seal2", displayName = "Тусклая радиационная печать", price_coin = 1500.00, price_ema = 50.00 },
  { internalName = "dwcity:Radio_seal", displayName = "Радиационная печать", price_coin = 1500.00, price_ema = 50.00 },
  { internalName = "dwcity:Power_seal2", displayName = "Тусклая печать силы", price_coin = 1000.00, price_ema = 2611.00 },
  { internalName = "dwcity:Power_seal", displayName = "Печать силы", price_coin = 1000.00, price_ema = 2611.00 },
  { internalName = "dwcity:Nano_seal2", displayName = "Тусклая нано-печать", price_coin = 1468.20, price_ema = 146.00 },
  { internalName = "dwcity:Nano_seal", displayName = "Нано-печать", price_coin = 1468.20, price_ema = 146.00 },
  { internalName = "dwcity:High_technology_seal_seal2", displayName = "Тусклая высокотехнологическая печать", price_coin = 500.00, price_ema = 72.00 },
  { internalName = "dwcity:High_technology_seal_seal", displayName = "Высокотехнологическая печать", price_coin = 500.00, price_ema = 72.00 },
  { internalName = "dwcity:Dragon_seal2", displayName = "Тусклая печать дракона", price_coin = 5000.00, price_ema = 200.00 },
  { internalName = "dwcity:Dragon_seal", displayName = "Печать дракона", price_coin = 5000.00, price_ema = 200.00 },
  { internalName = "dwcity:Flux_seal2", displayName = "Тусклая флаксовая печать", price_coin = 800.00, price_ema = 60.00 },
  { internalName = "dwcity:Flux_seal", displayName = "Флаксовая печать", price_coin = 800.00, price_ema = 60.00 },
  { internalName = "dwcity:Lamp_seal2", displayName = "Тусклая печать света",  price_coin = 555.00, price_ema = 20.00 },
  { internalName = "dwcity:Lamp_seal", displayName = "Печать света",  price_coin = 555.00, price_ema = 20.00 },
  { internalName = "dwcity:Bee_seal2", displayName = "Тусклая пчелиная печать",  price_coin = 1000.00, price_ema = 30.00 },
  { internalName = "dwcity:Bee_seal", displayName = "Пчелиная печать",  price_coin = 1000.00, price_ema = 30.00 },
  { internalName = "dwcity:Liquid_seal2", displayName = "Тусклая жидкостная печать",  price_coin = 190.00, price_ema = 1.00 },
  { internalName = "dwcity:Liquid_seal", displayName = "Жидкостная печать",  price_coin = 190.00, price_ema = 1.00 },
  { internalName = "dwcity:Cube_seal2", displayName = "Тусклая кубическая печать",  price_coin = 1000.00, price_ema = 0.00 },
  { internalName = "dwcity:Cube_seal", displayName = "Кубическая печать",  price_coin = 1000.00, price_ema = 0.00 },
  { internalName = "dwcity:Machine_seal2", displayName = "Тусклая механическая печать", price_coin = 400.00, price_ema = 28.00 },
  { internalName = "dwcity:Machine_seal", displayName = "Механическая печать", price_coin = 400.00, price_ema = 28.00 },
  { internalName = "dwcity:Optic_seal2", displayName = "Тусклая оптическая печать", price_coin = 3000.00, price_ema = 75.00 },
  { internalName = "dwcity:Optic_seal", displayName = "Оптическая печать", price_coin = 3000.00, price_ema = 75.00 },
  { internalName = "dwcity:Chest_seal2", displayName = "Тусклая печать безопастности",  price_coin = 360.00, price_ema = 4.00 },
  { internalName = "dwcity:Chest_seal", displayName = "Ппечать безопастности",  price_coin = 360.00, price_ema = 4.00 },
  { internalName = "dwcity:Food_seal2", displayName = "Тусклая печать голода", price_coin = 90.00, price_ema = 1.00 },
  { internalName = "dwcity:Food_seal", displayName = "Печать голода", price_coin = 90.00, price_ema = 1.00 },
  { internalName = "dwcity:Dnk_seal2", displayName = "Тусклая печать ДНК", price_coin = 1125.00, price_ema = 12.00 },
  { internalName = "dwcity:Dnk_seal", displayName = "Печать ДНК", price_coin = 1125.00, price_ema = 12.00 },
  { internalName = "dwcity:Sword_seal2", displayName = "Тусклая печать обороны", price_coin = 180.00, price_ema = 2.00 },
  { internalName = "dwcity:Sword_seal", displayName = "Печать обороны", price_coin = 180.00, price_ema = 2.00 },
  { internalName = "dwcity:Flower_seal2", displayName = "Тусклая печать розы",  price_coin = 175.00, price_ema = 2.00 },
  { internalName = "dwcity:Flower_seal", displayName = "Печать розы",  price_coin = 175.00, price_ema = 2.00 },
  { internalName = "dwcity:Death_seal2", displayName = "Тусклая печать смерти", price_coin = 438.90, price_ema = 18.00 },
  { internalName = "dwcity:Death_seal", displayName = "Печать смерти", price_coin = 438.90, price_ema = 18.00 },
  { internalName = "luxinfineitems:AdvancedEnergyCell", displayName = "Базовая энергетическая ячейка", price = 125.09, currency = "res", damage = 0 },
  { internalName = "EnderIO:itemPowerConduit", displayName = "Энергопровод из вибрирующего сплава ", price = 1.00, currency = "res", damage = 2 },
  { internalName = "metadrive:block_ic2_1_solar_panel", displayName = "Индустриальная солнечная панель II уровня", price = 156.00, currency = "res" },
  { internalName = "metadrive:block_ic2_2_solar_panel", displayName = "Индустриальная солнечная панель III уровня", price = 1300.00, currency = "res" },
  { internalName = "ic2:reactormoxquad", displayName = "Счетверённый топливный стержень (МОХ)", price = 60.00, currency = "res" },
  { internalName = "extracells:storage.component", displayName = "1024k МЭ жидкостный компонент хранилища", price = 3750.00 , currency = "res", damage = 1 },
  { internalName = "extracells:storage.component", displayName = "1024k МЭ компонент хранилища", price = 325.59, currency = "res", damage = 9 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "16K МЭ компонент хранения", price_coin = 90.00, price_ema = 0.00, damage = 37 },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.16k", displayName = "16K МЭ ячейка хранения", price = 11.64, currency = "res" },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "16K хранилище создания", price = 12.168, currency = "res" },
  { internalName = "extracells:storage.component", displayName = "16K МЭ жидкостный компонент хранилища", price = 9.405, currency = "res", damage = 6 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "1K МЭ компонент хранения", price_coin = 7.50, price_ema = 0.00, damage = 35 },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.1k", displayName = "1K МЭ ячейка хранения", price = 1.61, currency = "res" },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "1K хранилище создания", price = 2.208, currency = "res" },
  { internalName = "extracells:storage.component", displayName = "1K МЭ жидкостный компонент хранилища", price = 0.85, currency = "res", damage = 4 },
  { internalName = "extracells:storage.component", displayName = "256K МЭ жидкостный компонент хранилища", price = 900.00, currency = "res", damage = 8 },
  { internalName = "extracells:storage.component", displayName = "256K МЭ компонент хранилища", price = 145.83, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "4K МЭ компонент хранения", price_coin = 27.00, price_ema = 0.00, damage = 36 },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.4k", displayName = "4K МЭ ячейка хранения", price = 4.02, currency = "res" },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "4K хранилище создания", price = 4.548, currency = "res", damage = 1 },
  { internalName = "extracells:storage.component", displayName = "4K МЭ жидкостный компонент хранилища", price = 2.97, currency = "res", damage = 5 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "64K МЭ компонент хранения", price_coin = 281.00, price_ema = 2.00, damage = 38 },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.64k", displayName = "64K МЭ ячейка хранения", price_coin = 288.00, price_ema = 0.00 },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "64K хранилище создания", price = 36.487, currency = "res", damage = 3 },
  { internalName = "extracells:storage.component", displayName = "64K МЭ жидкостный компонент хранилища", price_coin = 261.00, price_ema = 0.00, damage = 7 },
  { internalName = "extracells:storage.fluid", displayName = "МЭ 64Кб жидкостное хранилище", price_coin = 460.00, price_ema = 0.00, damage = 3 },
  { internalName = "extracells:storage.casing", displayName = "Жидкостный корпус хранилища", price_coin = 40.00, price_ema = 0.00, damage = 1 },
  { internalName = "luxinfineitems:advancedCraftingStorage", displayName = "Хранилище создания МК1", price_coin = 854.56, price_ema = 1.74 },
  { internalName = "luxinfineitems:advancedCraftingStorage", displayName = "Хранилище создания МК2", price_coin = 1554.56, price_ema = 2.74 },
  { internalName = "luxinfineitems:advancedCraftingAccelerator", displayName = "Блок обработки создания МК1", price = 7.54, currency = "res" },
  { internalName = "luxinfineitems:advancedCraftingAccelerator", displayName = "Блок обработки создания МК2", price = 28.41, currency = "res", damage = 1 },
  { internalName = "dwcity:Chip_16bit", displayName = "16-битный чип", price = 25.25, currency = "res" },
  { internalName = "dwcity:Chip_32bit", displayName = "32-битный чип", price = 65.25, currency = "res" },
  { internalName = "dwcity:Chip_64bit", displayName = "64-битный чип", price = 125.22, currency = "res" },
  { internalName = "minecraft:iron_ingot", displayName = "Железный слиток", price = 0.22, currency = "res", },
  { internalName = "EnderIO:blockSliceAndSplice", displayName = "Отрубатель и сращиватель", price = 4.73, currency = "res" },
  { internalName = "minecraft:nether_wart", displayName = "Адский нарост", price = 1.00, currency = "res" },
  { internalName = "dwcity:Akvamarin", displayName = "Аквамарин", price = 170.00, currency = "res" },
  { internalName = "Genetics:labMachine", displayName = "Акклиматизатор", price = 4.72, currency = "res" },
  { internalName = "IC2:itemArmorBatpack", displayName = "Аккумуляторный ранец", price = 2.47, currency = "res" },
  { internalName = "Forestry:thermionicTubes", displayName = "Алмазная электронная лампа", price = 0.57, currency = "res" },
  { internalName = "IC2:itemToolDDrill", displayName = "Алмазный бур", price = 8.58, currency = "res" },
  { internalName = "IronChest:BlockIronChest", displayName = "Алмазный сундук", price = 2.64, currency = "res" },
  { internalName = "IC2:itemCropnalyzer", displayName = "Анализатор агрокультур", price = 5.70, currency = "res" },
  { internalName = "AdvancedSolarPanel:asp_crafting_items", displayName = "Армированная железная пластина", price = 8.8, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Базовая карта", price = 0.38, currency = "res", damage = 25 },
  { internalName = "dwcity:Basic_plan", displayName = "Базовый чертёж", price = 21.00, currency = "res" },
  { internalName = "BinnieCore:containerCylinder", displayName = "Баллон сырой ДНК", price = 2.75, currency = "res" },
  { internalName = "ae2wct:infinityBoosterCard", displayName = "Бесконечная карта усиления", price = 1489.37, currency = "res" },
  { internalName = "extracells:terminal.fluid.wireless", displayName = "Беспроводной МЭ жидкостный терминал", price = 21.36, currency = "res" },
  { internalName = "extracells:terminal.universal.wireless", displayName = "Беспроводной МЭ универсальный терминал", price = 22.51, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Беспроводной приёмник", price = 3.32, currency = "res", damage = 41 },
  { internalName = "appliedenergistics2:item.ToolWirelessTeminal", displayName = "Беспроводной терминал", price = 21.25, currency = "res" },
  { internalName = "ae2wct:wirelessCraftingTerminal", displayName = "Беспроводной терминал создания", price = 483.92, currency = "res" },
  { internalName = "appliedenergistics2:item.ToolBiometricCard", displayName = "Биометрическая карта", price = 10.99, currency = "res" },
  { internalName = "IC2:blockMetal", displayName = "Блок закалённого железа", price = 1.98, currency = "res", damage = 5 },
  { internalName = "appliedenergistics2:tile.BlockCraftingUnit", displayName = "Блок обработки создания", price = 15.4, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCraftingUnit", displayName = "Блок создания", price = 11.00, currency = "res" },
  { internalName = "ThermalExpansion:material", displayName = "Богатое удобрение", price = 0.11, currency = "res" },
  { internalName = "DraconicEvolution:wyvernBoots", displayName = "Ботинки Виверны", price = 485.16, currency = "res" },
  { internalName = "IC2:itemPlate", displayName = "Бронзовая пластина", price = 1.00, currency = "res", damage = 2 },
  { internalName = "IC2:itemIngot", displayName = "Бронзовый слиток", price = 1.00, currency = "res", damage = 2 },
  { internalName = "minecraft:cobblestone", displayName = "Булыжник", price = 0.01, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Бурановый порошок", price_coin = 0.00, price_ema = 0.20, damage = 1025 },
  { internalName = "ThermalFoundation:material", displayName = "Бурановый стержень", price_coin = 0.00, price_ema = 0.20, damage = 1024 },
  { internalName = "minecraft:bucket", displayName = "Ведро", price = 0.33, currency = "res" },
  { internalName = "minecraft:crafting_table", displayName = "Верстак", price = 1.55, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCellWorkbench", displayName = "Верстак для ячеек", price = 10.71, currency = "res" },
  { internalName = "EnderIO:blockCapBank", displayName = "Вибрирующий блок конденсаторов", price_coin = 225.00, price_ema = 1.00, damage = 3 },
  { internalName = "EnderIO:itemMaterial", displayName = "Вибрирующий кристалл", price_coin = 7.50, price_ema = 5.00, damage = 6 },
  { internalName = "EnderIO:itemAlloy", displayName = "Вибрирующий сплав", price = 7.50, currency = "res", damage = 2 },
  { internalName = "minecraft:hopper", displayName = "Воронка", price = 1.55, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockInscriber", displayName = "Высекатель", price = 1.78, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Логический процессор", price = 1.50, currency = "res", damage = 22 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Вычислительный процессор", price = 1.50, currency = "res", damage = 23 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Инженерный процессор", price = 4.50, currency = "res", damage = 24 },
  { internalName = "IC2:blockGenerator", displayName = "Генератор", price = 9.78, currency = "res" },
  { internalName = "MineFactoryReloaded:machine.1", displayName = "Генератор биотоплива", price = 20.64, currency = "res", damage = 11 },
  { internalName = "IC2:blockGenerator", displayName = "Геотермальный генератор", price = 10.24, currency = "res", damage = 1 },
  { internalName = "EnderIO:blockEndermanSkull", displayName = "Голова стража Края", price = 19.20, currency = "res" },
  { internalName = "minecraft:gravel", displayName = "Гравий", price = 0.11, currency = "res" },
  { internalName = "minecraft:dirt", displayName = "Земля", price = 0.01, currency = "res" },
  { internalName = "DraconicEvolution:draconiumFluxCapacitor", displayName = "Дракониевый флаксовый кондесатор", price_coin = 33969.40, price_ema = 105.05 },
  { internalName = "DraconicEvolution:draconium", displayName = "Дракониевый блок", price = 28.78, currency = "res" },
  { internalName = "DraconicEvolution:draconiumIngot", displayName = "Дракониевый слиток", price_coin = 3.92, price_ema = 2.66 },
  { internalName = "DraconicEvolution:draconicSword", displayName = "Драконий меч", price = 5285.34, currency = "res" },
  { internalName = "DraconicEvolution:draconicPickaxe", displayName = "Драконья кирка", price_coin = 38801.60, price_ema = 120.01 },
  { internalName = "DraconicEvolution:draconicAxe", displayName = "Драконий топор", price = 5537.34, currency = "res" },
  { internalName = "DraconicEvolution:draconicShovel", displayName = "Драконья лопата", price = 5339.68, currency = "res" },
  { internalName = "DraconicEvolution:draconicBow", displayName = "Драконий лук", price = 5670.28, currency = "res" },
  { internalName = "dwcity:Dragon_shard", displayName = "Драконивый кристалл", price_coin = 100.00, price_ema = 3.05 },
  { internalName = "DraconicEvolution:draconicHelm", displayName = "Драконий шлем", price_coin = 38663.81, price_ema = 119.55 },
  { internalName = "DraconicEvolution:draconicChest", displayName = "Драконий нагрудник", price_coin = 52646.36, price_ema = 162.05 },
  { internalName = "DraconicEvolution:wyvernLegs", displayName = "Драконьи поножи", price = 5359.67, currency = "res" },
  { internalName = "DraconicEvolution:wyvernBoots", displayName = "Драконьи ботинки", price = 5309.59, currency = "res" },
  { internalName = "DraconicEvolution:draconicStaffOfPower", displayName = "Драконий посох силы", price = 59923.00, currency = "res" },
  { internalName = "DraconicEvolution:draconicCore", displayName = "Драконье ядро", price = 20.0, currency = "res" },
  { internalName = "DraconicEvolution:wyvernPickaxe", displayName = "Кирка Виверны", price_coin = 1863.35, price_ema = 186.34 },
  { internalName = "dwcity:Granat", displayName = "Гранат", price = 45.3, currency = "res" },
  { internalName = "minecraft:red_mushroom", displayName = "Гриб", price = 0.1, currency = "res" },
  { internalName = "minecraft:gold_ingot", displayName = "Золотой слиток", price = 0.15, currency = "res" },
  { internalName = "Botany:pigment", displayName = "Зелёный краситель", price = 0.11, currency = "res", damage = 13 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал", price = 9.50, currency = "res", damage = 380 },
  { internalName = "appliedenergistics2:item.ItemBlockSecurity", displayName = "МЭ терминал безопасности", price = 120.00, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал интерфейсов", price = 16.00, currency = "res", damage = 480 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал создания", price = 11.00, currency = "res", damage = 360 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал шаблонов", price = 15.5, currency = "res", damage = 340 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ умный кабель - Изменчивый", price = 2.70, currency = "res", damage = 56 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ шина импорта", price = 6.20, currency = "res", damage = 240 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ шина экспорта", price = 5.5, currency = "res", damage = 260 },
  { internalName = "IC2:itemRecipePart", displayName = "Малый силовой агрегат", price = 17.50, currency = "res", damage = 3 },
  { internalName = "IC2:itemPlates", displayName = "Медная пластина", price = 0.11, currency = "res" },
  { internalName = "Forestry:thermionicTubes", displayName = "Медная электронная лампа", price = 0.65, currency = "res" },
  { internalName = "IC2:itemCable", displayName = "Медный провод", price = 0.05, currency = "res", damage = 1 },
  { internalName = "EnderIO:itemBasicCapacitor", displayName = "Мелодичный конденсатор", price = 25.79, currency = "res", damage = 4 },
  { internalName = "IC2:blockMachine2", displayName = "Металлоформовочный механизм", price = 27.00, currency = "res", damage = 4 },
  { internalName = "dwcity:Machine_seal2", displayName = "Механическая печать", price = 33.68, currency = "res" },
  { internalName = "DraconicEvolution:wyvernSword", displayName = "Меч Виверны", price = 498.65, currency = "res" },
  { internalName = "metadrive:module_fortune_luck_changer_tier_3", displayName = "Модуль удачи IV", price_coin = 1265.0, price_ema = 100, currency = "res" },
  { internalName = "dwcity:Module_seal", displayName = "Модульная печать", price = 16.8, currency = "res" },
  { internalName = "metadrive:block_molecular_transformer", displayName = "Молекулярный преобразователь", price = 403.50, currency = "res" },
  { internalName = "luxinfineitems:AEAdvMolecularAssembler", displayName = "Квантовый молекулярный сборщик", price_coin = 168.76, price_ema = 0.34, damage = 2 },
  { internalName = "appliedenergistics2:tile.BlockMolecularAssembler", displayName = "Молекулярный сборщик", price = 12.80, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCraftingMonitor", displayName = "Монитор создания", price = 1.73, currency = "res" },
  { internalName = "minecraft:carrot", displayName = "Морковь", price = 1.00, currency = "res" },
  { internalName = "ExtraBees:alveary", displayName = "Мутатор улья", price = 22.5, currency = "res" },
  { internalName = "IC2NuclearControl:ItemMultipleSensorKit", displayName = "Набор для счётчика энергии", price = 1.43, currency = "res" },
  { internalName = "IC2NuclearControl:ItemEnergySensorKit", displayName = "Набор для энергетического хранилища", price = 1.65, currency = "res" },
  { internalName = "ExtraBees:alveary", displayName = "Навес улья", price = 22.75, currency = "res", damage = 2 },
  { internalName = "DraconicEvolution:wyvernChest", displayName = "Нагрудник Виверны", price_coin = 2603.7, price_ema = 260.37 },
  { internalName = "IC2:itemArmorQuantumChestplate", displayName = "Квантовая кираса", price_coin = 1655.29, price_ema = 29.21 },
  { internalName = "IC2:itemArmorQuantumBoots", displayName = "Квантовые ботинки", price_coin = 814.98, price_ema = 14.30 },
  { internalName = "IC2:itemArmorNanoBoots", displayName = "Нано-ботинки", price = 60.70, currency = "res" },
  { internalName = "IC2:itemArmorQuantumHelmet", displayName = "Квантовый шлем", price_coin = 897.26, price_ema = 15.83 },
  { internalName = "IC2:itemArmorNanoChestplate", displayName = "Нано-кираса", price = 74.00, currency = "res" },
  { internalName = "IC2:itemArmorLegas", displayName = "Нано-поножи", price = 60.93, currency = "res" },
  { internalName = "IC2:itemNanoSaber", displayName = "Нано-сабля", price = 65.00, currency = "res" },
  { internalName = "IC2:itemArmorNanoHelmet", displayName = "Нано-шлем", price = 146.00, currency = "res" },
  { internalName = "DraconicEvolution:energyInfuser", displayName = "Наполнитель энергии", price_coin = 0.00, price_ema = 59.09 },
  { internalName = "EnderIO:itemAlloy", displayName = "Наэлектризованная сталь", price = 2.00, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockSkyStone", displayName = "Небесный камень", price = 0.22, currency = "res" },
  { internalName = "IC2:itemBatREDischarged", displayName = "Незаряженный аккумулятор", price = 3.30, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Никелевый слиток", price = 2.00, currency = "res", damage = 68 },
  { internalName = "Forestry:alveary", displayName = "Обогреватель улья", price = 20.86, currency = "res", damage = 4 },
  { internalName = "minecraft:obsidian", displayName = "Обсидиан", price = 0.12, currency = "res" },
  { internalName = "IC2:itemPlates", displayName = "Обсидиановая пластина", price = 1.00, currency = "res", damage = 7 },
  { internalName = "IC2:itemDust", displayName = "Обсидиановая пыль", price = 0.11, currency = "res", damage = 11 },
  { internalName = "Forestry:thermionicTubes", displayName = "Обсидиановая электронная лампа", price = 0.42, currency = "res", damage = 6 },
  { internalName = "metadrive:block_solar_panel_combiner", displayName = "Объединитель солнечных панелей", price = 61.66, currency = "res" },
  { internalName = "Forestry:thermionicTubes", displayName = "Огненная электронная лампа", price = 0.65, currency = "res", damage = 7 },
  { internalName = "minecraft:ender_eye", displayName = "Око Эндера", price = 0.66, currency = "res" },
  { internalName = "ThermalFoundation:tool.fishingRodTin", displayName = "Оловянная пластина", price = 0.11, currency = "res", damage = 1 },
  { internalName = "Botany:insulatedTube", displayName = "Оловянная электронная лампа", price = 0.65, currency = "res", damage = 1 },
  { internalName = "ExtraBees:alveary", displayName = "Осветитель улья", price = 20.16, currency = "res", damage = 3 },
  { internalName = "EnderIO:itemBasicCapacitor", displayName = "Основной конденсатор", price = 10.64, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Основной корпус механизма", price = 8.00, currency = "res" },
  { internalName = "EnderIO:itemBasicFilterUpgrade", displayName = "Основной предметный фильтр", price = 6.00, currency = "res" },
  { internalName = "IC2:itemDensePlates", displayName = "Плотная лазуритовая пластина", price = 1.95, currency = "res", damage = 8 },
  { internalName = "IC2:itemDensePlates", displayName = "Плотная обсидиановая пластина", price = 1.95, currency = "res", damage = 7 },
  { internalName = "dwcity:Enderium_plate2", displayName = "Плотная эндериумная пластина", price = 8.96, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockDenseEnergyCell", displayName = "Плотная энергетическая ячейка", price = 16.88, currency = "res" },
  { internalName = "Forestry:factory", displayName = "Плотник", price = 50.56, currency = "res", damage = 1 },
  { internalName = "EnderIO:blockPainter", displayName = "Покрасочный механизм", price = 2.53, currency = "res" },
  { internalName = "DraconicEvolution:wyvernLegs", displayName = "Поножи Виверны", price = 537.638, currency = "res" },
  { internalName = "minecraft:gunpowder", displayName = "Порох", price = 0.22, currency = "res" },
  { internalName = "minecraft:piston", displayName = "Поршень", price = 0.165, currency = "res" },
  { internalName = "EnderIO:itemTravelStaff", displayName = "Посох путешествия", price = 5.95, currency = "res" },
  { internalName = "EnderIO:itemConduit", displayName = "Предметная труба", price = 0.66, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockEnergyAcceptor", displayName = "Приёмщик энергии", price = 1.26, currency = "res" },
  { internalName = "DraconicEvolution:awakenedCore", displayName = "Пробуждённое ядро", price_coin = 8537.27, price_ema = 44.93 },
  { internalName = "DraconicEvolution:draconiumIngot", displayName = "Пробуждённый дракониевый слиток", price_coin = 239.59, price_ema = 1.26, damage = 6525 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Продвинутая карта", price = 15.71, currency = "res", damage = 28 },
  { internalName = "Forestry:chipsets", displayName = "Продвинутая печатная плата", price = 10.66, currency = "res", damage = 1 },
  { internalName = "IC2:itemPartCircuiAdv", displayName = "Продвинутая электросхема", price = 10.96, currency = "res" },
  { internalName = "IC2:itemArmorAdvBatpack", displayName = "Продвинутый аккумуляторный ранец", price = 7.04, currency = "res" },
  { internalName = "ae2stuff:Inscriber", displayName = "Продвинутый высекатель", price = 76.21, currency = "res" },
  { internalName = "luxinfineitems:ExtendedPatternsEncoder", displayName = "Продвинутый кодировщик шаблонов", price = 420.0, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Продвинутый корпус механизма", price = 25.00, currency = "res", damage = 12 },
  { internalName = "metadrive:block_solar_panel_combiner", displayName = "Продвинутый объединитель солнечных панелей", price = 919.33, currency = "res", damage = 1 },
  { internalName = "MineFactoryReloaded:machine.1", displayName = "Производитель лавы", price = 3.63, currency = "res", damage = 5 },
  { internalName = "Forestry:frameImpregnated", displayName = "Пропитанная рамка", price = 1.77, currency = "res" },
  { internalName = "Forestry:thermionicTubes", displayName = "Прорезиненная электронная лампа", price = 0.01, currency = "res", damage = 8 },
  { internalName = "EnderIO:blockTransceiver", displayName = "Пространственный приёмопередатчик", price = 14.87, currency = "res" },
  { internalName = "OpenComputers:item", displayName = "Видеокарта (1-ый уровень)", price = 20.52, currency = "res", damage = 8 },
  { internalName = "OpenComputers:item", displayName = "Видеокарта (2-ой уровень)", price = 40.62, currency = "res", damage = 9 },
  { internalName = "OpenComputers:item", displayName = "Видеокарта (3-ий уровень)", price = 80.15, currency = "res", damage = 10 },
  { internalName = "OpenComputers:item", displayName = "Процессор с видеокартой (APU) (2-ой уровень)", price = 230.95, currency = "res", damage = 102 },
  { internalName = "OpenComputers:item", displayName = "Процессор с видеокартой (APU) (Творческий)", price = 998.36, currency = "res", damage = 103 },
  { internalName = "EnderIO:itemAlloy", displayName = "Пульсирующее железо", price = 6.00, currency = "res", damage = 5 },
  { internalName = "minecraft:glass_bottle", displayName = "Пустая капсула", price = 0.33, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Пустой шаблон", price = 10.00, currency = "res",  damage = 52 },
  { internalName = "dwcity:Bee_seal2", displayName = "Пчелиная печать", price = 199.2, currency = "res" },
  { internalName = "Forestry:beeswax", displayName = "Пчелиный воск", price_coin = 0.00, price_ema = 0.05 },
  { internalName = "Forestry:alveary", displayName = "Пчелиный улей", price = 25.0, currency = "res" },
  { internalName = "minecraft:wheat", displayName = "Пшеница", price = 0.01, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Пыль криотеума", price_coin = 0.00, price_ema = 0.20, damage = 513 },
  { internalName = "ThermalFoundation:material", displayName = "Пыль пиротеума", price_coin = 0.00, price_ema = 0.20, damage = 512 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Пыль небесного камня", price = 0.77, currency = "res",  damage = 45 },
  { internalName = "IC2:reactorVentGold", displayName = "Разогнанный теплоотвод", price = 2.95, currency = "res" },
  { internalName = "IC2:itemRecipePart", displayName = "Катушка", price_coin = 3.40, price_ema = 0.00 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Основная)", price = 17.07, currency = "res" },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Усиленная)", price = 34.14, currency = "res", damage = 1 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Укреплённая)", price = 51.21, currency = "res", damage = 2 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Резонирующая)", price = 68.28, currency = "res", damage = 3 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка свинцовой энергетической ячейки", price = 1.45, currency = "res", damage = 4 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка тессаракта (Полная)", price = 7.13, currency = "res", damage = 11 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вторичная отдающая катушка", price = 7.77, currency = "res", damage = 80 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вторичная принимающая катушка", price = 7.00, currency = "res", damage = 128 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вторичное сито", price = 7.48, currency = "res", damage = 112 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вулканический катализатор", price = 7.00, currency = "res", damage = 313 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированная воронка", price = 7.39, currency = "res", damage = 1 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированная красная схема", price = 7.99, currency = "res", damage = 32 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированная модульная структура", price = 7.45, currency = "res", damage = 16 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированный сервомеханизм", price = 7.25, currency = "res" },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Камера аннулирования", price = 7.65, currency = "res", damage = 144 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Канал отдающей катушки", price = 7.65, currency = "res", damage = 48 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Ограничитель поля намагничивания", price = 7.27, currency = "res", damage = 49 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Оптимизация флаксовой связи", price = 7.36, currency = "res", damage = 65 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Отклик гиросервомеханизма", price = 1.23, currency = "res", damage = 114 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Пирокластическое генерирование", price = 7.54, currency = "res", damage = 314 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Пространственно-временной унификатор", price = 20.35, currency = "res", damage = 130 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Разогнанный модульный редуктор", price = 11.14, currency = "res", damage = 129 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Регулятор криогенной катушки", price = 11.43, currency = "res", damage = 66 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Стабилизированная рамка", price = 7.68, currency = "res", damage = 113 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Тривекционная камера", price = 7.47, currency = "res", damage = 256 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Усилитель модуляции флакса", price = 7.47, currency = "res", damage = 81 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Ускоренная экструзия", price = 7.47, currency = "res", damage = 312 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Фазовый резонатор", price = 708.48, currency = "res" },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Флаксовый усилитель криогенной катушки", price = 1.43, currency = "res", damage = 82 },
  { internalName = "IC2:blockReactorChamber", displayName = "Реакторная камера", price = 102.00, currency = "res" },
  { internalName = "IC2:reactorPlating", displayName = "Реакторная обшивка", price = 10.63, currency = "res" },
  { internalName = "IC2:blockreactorvessel", displayName = "Реакторный корпус", price = 0.43, currency = "res" },
  { internalName = "IC2:blockReactorAccessHatch", displayName = "Реакторный люк", price = 1.1, currency = "res" },
  { internalName = "IC2:blockReactorFluidPort", displayName = "Реакторный насос", price = 1.32, currency = "res" },
  { internalName = "IC2:blockReactorRedstonePort", displayName = "Реакторный проводник красного сигнала", price = 1.55, currency = "res" },
  { internalName = "IC2:reactorVentCore", displayName = "Реакторный теплоотвод", price = 2.88, currency = "res" },
  { internalName = "EnderIO:blockReservoir", displayName = "Резервуар", price = 1.00, currency = "res" },
  { internalName = "IC2:itemRubber", displayName = "Резина", price = 0.03, currency = "res" },
  { internalName = "ThermalExpansion:Workbench", displayName = "Резонирующий вулканический пресс", price = 8.92, currency = "res", damage = 4 },
  { internalName = "ThermalExpansion:Tank", displayName = "Резонирующий переносной бак", price_coin = 0.00, price_ema = 80.68, damage = 4 },
  { internalName = "ThermalExpansion:Strongbox", displayName = "Резонирующий сейф", price = 5.29, currency = "res", damage = 4 },
  { internalName = "ThermalExpansion:capacitor", displayName = "Резонирующий флаксовый конденсатор", price = 4.6, currency = "res", damage = 5 },
  { internalName = "IC2:blockMachine2", displayName = "Рудопромывочный механизм", price = 38.40, currency = "res", damage = 5 },
  { internalName = "dwcity:Sostav", displayName = "Рыбий жир", price = 20.00, currency = "res" },
  { internalName = "MineFactoryReloaded:machine.0", displayName = "Рыболов", price = 29.00, currency = "res", damage = 1 },
  { internalName = "minecraft:lever", displayName = "Рычаг", price = 0.01, currency = "res" },
  { internalName = "MineFactoryReloaded:rubberwood.sapling", displayName = "Саженец гевеи", price = 0.11, currency = "res" },
  { internalName = "EnderIO:itemMaterial", displayName = "Самородок вибрирующего сплава", price = 0.83, currency = "res", damage = 4 },
  { internalName = "AdvancedSolarPanel:asp_crafting_items", displayName = "Саннариум", price_coin = 89.10, price_ema = 0.90 },
  { internalName = "minecraft:sugar", displayName = "Сахар", price_coin = 0.00, price_ema = 0.02 },
  { internalName = "minecraft:reeds", displayName = "Сахарный тростник", price_coin = 0.00, price_ema = 0.02 },
  { internalName = "IC2:blockMachine3", displayName = "Сборщик урожая", price = 30.49, currency = "res", damage = 7 },
  { internalName = "IC2:itemPlates", displayName = "Свинцовая пластина", price = 1.00, currency = "res", damage = 6 },
  { internalName = "IC2:itemIngot", displayName = "Свинцовый слиток", price = 0.15, currency = "res", damage = 5 },
  { internalName = "EnderIO:itemMaterial", displayName = "Связующий элемент труб", price = 0.06, currency = "res", damage = 1 },
  { internalName = "EnderIO:blockSoulBinder", displayName = "Связыватель душ", price = 10.56, currency = "res" },
  { internalName = "minecraft:slime_ball", displayName = "Сгусток слизи", price_coin = 0.00, price_ema = 0.05 },
  { internalName = "IC2:reactorUraniumDual", displayName = "Сдвоенный топливный стержень (Уран)", price = 3.63, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Селитра", price = 1.55, currency = "res", damage = 17 },
  { internalName = "minecraft:wheat_seeds", displayName = "Семена пшеницы", price = 0.01, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Сера", price = 1.55, currency = "res", damage = 16 },
  { internalName = "OpenComputers:item", displayName = "Сетевая карта", price = 10.67, currency = "res", damage = 11 },
  { internalName = "MineFactoryReloaded:machine.0", displayName = "Комбайн", price = 30.00, currency = "res", damage = 2 },
  { internalName = "MineFactoryReloaded:machine.0", displayName = "Сеятель", price = 26.00, currency = "res" },
  { internalName = "IC2:itemRecipePart", displayName = "Силовой агрегат", price = 24.1, currency = "res", damage = 2 },
  { internalName = "PowerUtils:BlockMain", displayName = "Силовой конвертер", price = 123.45, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Синаловый слиток", price = 1.30, currency = "res", damage = 74 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Сингулярность", price = 1100.00, currency = "res", damage = 47 },
  { internalName = "Forestry:alveary", displayName = "Сито улья", price = 26.6, currency = "res", damage = 7 },
  { internalName = "IC2:blockMetal:3", displayName = "Слиток закалённого железа", price = 2.00, currency = "res", damage = 3 },
  { internalName = "IC2:itemIngot", displayName = "Слиток урана", price = 4.00, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Слиток эндериума", price = 9.00, currency = "res", damage = 76 },
  { internalName = "ThermalFoundation:material", displayName = "Смесь эндериума", price_coin = 0.00, price_ema = 0.09, damage = 44 },
  { internalName = "minecraft:snowball", displayName = "Снежок", price = 0.01, currency = "res" },
  { internalName = "EnderIO:itemExtractSpeedUpgrade", displayName = "Снижение скорости для предметной трубы", price = 1.62, currency = "res", damage = 1 },
  { internalName = "luxinfineitems:advanced_portable_storage_cell_2", displayName = "Совершенная переносная ячейка", price = 3160.00, currency = "res" },
  { internalName = "luxinfineitems:AEUltInterface", displayName = "Совершенный МЭ интерфейс", price = 180.00, currency = "res" },
  { internalName = "luxinfineitems:AEAdvMolecularAssembler", displayName = "Совершенный молекулярный сборщик", price_coin = 57.82, price_ema = 0.12, damage = 1 },
  { internalName = "OpenComputers:item", displayName = "Соединённая карта", price = 10.33, currency = "res", damage = 51 },
  { internalName = "Forestry:factory", displayName = "Соковыжималка", price = 12.63, currency = "res", damage = 5 },
  { internalName = "IC2:blockGenerator", displayName = "Солнечная панель", price = 19.00, currency = "res", damage = 3 },
  { internalName = "IC2:blockMachine3", displayName = "Солнечный опреснитель", price = 10.32, currency = "res", damage = 3 },
  { internalName = "EnderIO:itemAlloy", displayName = "Сплав из красного камня", price = 5.06, currency = "res", damage = 3 },
  { internalName = "IC2:blockMachine2", displayName = "Термальная центрифуга", price = 113.20, currency = "res", damage = 3 },
  { internalName = "dwcity:Topaz", displayName = "Топаз", price = 5.00, currency = "res" },
  { internalName = "IC2:itemTritiumCell", displayName = "Топливный стержень (Тритий)", price_coin = 50.50, price_ema = 1.00 },
  { internalName = "IC2:reactoryUraniumSimple", displayName = "Топливный стержень (Уран)", price = 5.76, currency = "res" },
  { internalName = "IC2:blockPersonal", displayName = "Торговый аппарат", price_coin = 0.00, price_ema = 26.67, damage = 1 },
  { internalName = "dwcity:ThoriumBlock", displayName = "Ториевый блок", price = 63.00, currency = "res" },
  { internalName = "dwcity:Thorium_ingot", displayName = "Ториевый слиток", price = 7.00, currency = "res" },
  { internalName = "IC2:blockElectric", displayName = "Трансформатор BH", price = 19.10, currency = "res", damage = 5 },
  { internalName = "IC2:blockElectric", displayName = "Трансформатор HH", price = 4.00, currency = "res", damage = 3 },
  { internalName = "IC2:blockElectric", displayName = "МФЭХ", price = 356.00, currency = "res", damage = 2 },
  { internalName = "IC2:blockElectric", displayName = "МФЭ", price = 84.8, currency = "res", damage = 1 },
  { internalName = "IC2:blockElectric", displayName = "Трансформатор CH", price = 8.6, currency = "res", damage = 4 },
  { internalName = "minecraft:pumpkin", displayName = "Тыква", price = 1.00, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "Тёмная осветительная панель", price = 0.24, currency = "res", damage = 200 },
  { internalName = "EnderIO:itemAlloy", displayName = "Тёмная сталь", price = 2.20, currency = "res", damage = 6 },
  { internalName = "dwcity:Dark_plate", displayName = "Тёмное покрытие", price_coin = 0.00, price_ema = 5.40 },
  { internalName = "dwcity:Dark_dust", displayName = "Тёмный порошок", price = 2.20, currency = "res" },
  { internalName = "IC2:itemwcarbonrotor", displayName = "Углеволоконный ротор ветрогенератора", price_coin = 0.00, price_ema = 16.2 },
  { internalName = "IC2:itemPartCarbonPlate", displayName = "Углепластик", price = 4.00, currency = "res" },
  { internalName = "IC2:itemPartCarbonMesh", displayName = "Углеткань", price = 2.00, currency = "res" },
  { internalName = "MineFactoryReloaded:machiner.0", displayName = "Удобритель", price = 30.00, currency = "res", damage = 4 },
  { internalName = "IC2:blockAlloyGlass", displayName = "Укреплённое стекло", price = 10.43, currency = "res" },
  { internalName = "IC2:blockAlloy", displayName = "Укреплённый камень", price = 0.55, currency = "res" },
  { internalName = "MineFactoryReloaded:upgrader.radius", displayName = "Улучшение (Медь)", price = 0.45, currency = "res", damage = 3 },
  { internalName = "EnderIO:itemExtractSpeedUpgrade", displayName = "Улучшение скорости для предметной трубы", price = 1.32, currency = "res" },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Втягиватель", price = 12.40, currency = "res", damage = 6 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Выталкиватель", price = 12.40, currency = "res", damage = 3 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Выталкиватель жидкостей", price = 12.48, currency = "res", damage = 4 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Инвертор сигнала красного камня", price = 4.00, currency = "res", damage = 5 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Трансформатор", price = 1.43, currency = "res", damage = 1 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Ускоритель", price = 159.40, currency = "res" },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Энергохранитель", price = 2.25, currency = "res", damage = 2 },
  { internalName = "luxinfineitems:AECompressedSpeedCard", displayName = "Улучшенная карта ускорения", price = 4.22, currency = "res" },
  { internalName = "luxinfineitems:advanced_portavle_storage_cell_0", displayName = "Улучшенная переносная ячейка", price = 24.35, currency = "res" },
  { internalName = "luxinfineitems:AEAdvInterface", displayName = "Улучшенный МЭ интерфейс", price = 27.00, currency = "res" },
  { internalName = "GraviSuite:advDDrill", displayName = "Улучшенный алмазный бур", price = 468.00, currency = "res" },
  { internalName = "GraviSuite:advLappack", displayName = "Улучшенный лаппак", price = 24.104, currency = "res" },
  { internalName = "luxinfineitems:AEAdvMolecularAssembler", displayName = "Улучшенный молекулярный сборщик", price = 3.46, currency = "res" },
  { internalName = "luxinfineitems:advancedDrive", displayName = "Улучшенный МЭ накопитель", price = 108.00, currency = "res" },
  { internalName = "GraviSuite:advNanoChestPlate", displayName = "Улучшенный наножилет", price = 73.77, currency = "res" },
  { internalName = "dwcity:Legend_plan", displayName = "Легендарный чертёж", price_coin = 909.52, price_ema = 22.74 },
  { internalName = "dwcity:Rare_plan", displayName = "Улучшенный чертёж", price = 52.00, currency = "res" },
  { internalName = "IC2:itemArmorLappack", displayName = "Ультимейт лаппак", price = 200.05, currency = "res" },
  { internalName = "IC2:itemFluidCell", displayName = "Универсальная жидкостная капсула", price = 0.22, currency = "res" },
  { internalName = "dwcity:Epic_plan", displayName = "Уникальный чертёж", price = 95.00, currency = "res" },
  { internalName = "IC2:itemUran238", displayName = "Уран-238", price = 1.00, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Усилитель беспроводного сигнала", price = 1.85, currency = "res", damage = 42 },
  { internalName = "GraviSuite:itemSimpleItem", displayName = "Ускоритель двигателя", price = 22.69, currency = "res", damage = 6 },
  { internalName = "appliedenergistics2:tile.BlockQuartzGrowthAccelerator", displayName = "Ускоритель роста кристаллов", price = 2.44, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Утилизатор", price = 14.68, currency = "res", damage = 11 },
  { internalName = "Genetics:misc", displayName = "Фермент", price_coin = 0.00, price_ema = 0.05, damage = 3 },
  { internalName = "EnderIO:blockFarmStation", displayName = "Фермерская станция", price = 6.63, currency = "res" },
  { internalName = "dwcity:Flux_plate", displayName = "Флаксовая пластина", price = 2.00, currency = "res" },
  { internalName = "dwcity:Flux_ingot", displayName = "Флаксовый слиток", price = 2.00, currency = "res" },
  { internalName = "DraconicEvolution:draconiumFluxCapacitor", displayName = "Флаксовый конденсатор Виверны", price_coin = 2250.20, price_ema = 404.52 },
  { internalName = "dwcity:Flux_ingot", displayName = "Флаксовый слиток", price = 9.00, currency = "res" },
  { internalName = "IC2:itemHops", displayName = "Хмель", price_coin = 0.00, price_ema = 0.01 },
  { internalName = "ExtraBees:alveary", displayName = "Хранитель рамок улья", price = 21.5, currency = "res", damage = 1 },
  { internalName = "OpenComputers:item", displayName = "Центральный процессор (ЦП) (3-ий уровень)", price_coin = 111.60, price_ema = 11.68, damage = 43 },
  { internalName = "Forestry:factory", displayName = "Центрифуга", price = 12.20, currency = "res", damage = 2 },
  { internalName = "IC2:itemFreq", displayName = "Частотный связыватель", price = 1.25, currency = "res" },
  { internalName = "minecraft:skull", displayName = "Череп скелета", price = 1.98, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Чистый изменчивый кристалл", price = 1.00, currency = "res", damage = 12 },
  { internalName = "MineFactoryReloaded:pinkslime", displayName = "Шарик розовой слизи", price = 1.87, currency = "res" },
  { internalName = "IC2:itemToolDrill", displayName = "Шахтёрский бур", price = 3.68, currency = "res" },
  { internalName = "Thaumcraft:ItemResource", displayName = "Шахтёрский лазер", price_coin = 100.00, price_ema = 6.86 },
  { internalName = "ThermalFoundation:material", displayName = "Ламиумовый слиток", price_coin = 2.00, price_ema = 0.00, damage = 75 },
  { internalName = "ThermalFoundation:material", displayName = "Инваровый слиток", price_coin = 1.00, price_ema = 0.00, damage = 72 },
  { internalName = "minecraft:wool", displayName = "Шерсть", price = 0.11, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Шестерня из эндериума", price = 4.07, currency = "res", damage = 140 },
  { internalName = "ThermalExpansion:material", displayName = "Шлак", price = 0.11, currency = "res", damage = 514 },
  { internalName = "DraconicEvolution:wyvernHelm", displayName = "Шлем Виверны", price_coin = 2157.8, price_ema = 215.78 },
  { internalName = "IC2:blockMachine", displayName = "Экстрактор", price = 11.80, currency = "res", damage = 4 },
  { internalName = "Genetics:labMachine", displayName = "Экстрактор ДНК", price = 4.59, currency = "res", damage = 3 },
  { internalName = "IC2:blockKineticGenerator", displayName = "Электрический кинетический генератор", price = 2.65, currency = "res", damage = 2 },
  { internalName = "IC2:itemRecipePart", displayName = "Электромотор", price = 8.7, currency = "res", damage = 1 },
  { internalName = "IC2:blockMachine", displayName = "Электропечь", price = 9.78, currency = "res", damage = 2 },
  { internalName = "IC2:itemPartCircuit", displayName = "Электросхема", price = 1.25, currency = "res" },
  { internalName = "ExtraBees:alveary", displayName = "Электротрансформатор улья", price = 24.0, currency = "res", damage = 6 },
  { internalName = "ThermalFoundation:tool.hoeElectrum", displayName = "Электрумовый слиток", price = 1.00, currency = "res", damage = 71 },
  { internalName = "dwcity:Dark_element", displayName = "Элемент тьмы", price = 394.84, currency = "res" },
  { internalName = "dwcity:Ender_eye", displayName = "Эндер глаз", price_coin = 0.00, price_ema = 17.50 },
  { internalName = "dwcity:Enderium_plate", displayName = "Эндериумная пластина", price = 10.00, currency = "res" },
  { internalName = "metadrive:neptunium_cindensator", displayName = "Эндериумный конденсатор", price = 298.78, currency = "res" },
  { internalName = "dwcity:Scattering_crystal", displayName = "Эндериумный хладагент", price = 3.35, currency = "res" },
  { internalName = "minecraft:end_stone", displayName = "Эндерняк", price = 0.11, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockEnergyCell", displayName = "Энергетическая ячейка", price = 2.85, currency = "res" },
  { internalName = "IC2:itemArmorEnergypack", displayName = "Энергетический ранец", price = 121.00, currency = "res" },
  { internalName = "EnderIO:itemAlloy", displayName = "Энергетический сплав", price = 2.00, currency = "res", damage = 1 },
  { internalName = "appliedenergistics2:tile.BlockQuartzLamp", displayName = "Энергичное кварцевое стекло", price = 3.45, currency = "res" },
  { internalName = "EnderIO:itemPowerConduitEndergy", displayName = "Энергопровод из кристаллического сплава 40960 RF/t", price = 1.65, currency = "res", damage = 8 },
  { internalName = "IC2:itemDust2", displayName = "Энергопыль", price = 2.21, currency = "res", damage = 2 },
  { internalName = "IC2:BatCrystal", displayName = "Энергетический кристалл", price_coin = 18.90, price_ema = 0.00 },
  { internalName = "IC2:blockElectric", displayName = "Энергохранилище", price = 10.20, currency = "res" },
  { internalName = "IC2:blockGenerator", displayName = "Ядерный реактор", price = 361.69, currency = "res", damage = 5 },
  { internalName = "appliedenergistics2:tile.ItemMultiMaterial", displayName = "Ядро истребления", price = 0.32, currency = "res", damage = 44 },
  { internalName = "minecraft:blaze_rod", displayName = "Стержень ифрита", price_coin = 4.50, price_ema = 0.05 },
  { internalName = "minecraft:ender_pearl", displayName = "Жемчуг Эндера", price_coin = 4.75, price_ema = 0.03 },
  { internalName = "minecraft:bone", displayName = "Кость", price_coin = 0.00, price_ema = 0.2 },
  { internalName = "Forestry:royalJelly", displayName = "Маточное молочко", price_coin = 0.00, price_ema = 0.05 },
  { internalName = "DraconicEvolution:draconicCore", displayName = "Драконье ядро", price_coin = 132.00, price_ema = 13.40 },
  { internalName = "minecraft:stone", displayName = "Камень", price = 0.02, currency = "res" }
}
